### PR TITLE
Set allowed puppet-epel version to < 5.0.0

### PR DESCRIPTION
**Pull request by yorickps**
Implement following PR to fix DNF
<https://github.com/voxpupuli/puppet-epel/pull/130>

### CODE REVIEW

**Comment by treydock** [comment]
I pushed some changes to master branch that should resolve the tests failing. Please merge in master or rebase against master.

**Comment by yorickps** [comment]
> I pushed some changes to master branch that should resolve the tests failing. Please merge in master or rebase against master.

Ok, thanks, I've rebased against master.

**Comment by treydock** [comment]
There are more issues with Python module < 6.3.0 and EPEL dependency. I'll fix in different pull request

**Comment by treydock** [comment]
Go ahead and rebase again, tests should be good now I think.

**Comment by yorickps** [comment]
> Go ahead and rebase again, tests should be good now I think.

Ok, thanks for the follow up :+1: . I've rebased against master again.

**Comment by treydock** [comment]
This will be released with v8.0.0 once Github Actions complete.

**Pull request merged**
